# ===============================
# SERVER CONFIG
# ===============================
server.port=${PORT:8080}

# ===============================
# MONGODB CONFIG
# ===============================
# spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/foodies}
# spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.data.mongodb.uri=mongodb+srv://foodiesuser:Foodies123@foodies.uoufnsh.mongodb.net/foodies?retryWrites=true&w=majority

# ===============================
# AWS CONFIG
# ===============================
aws.access.key=${AWS_ACCESS_KEY_ID:dummy}
aws.secret.key=${AWS_SECRET_ACCESS_KEY:dummy}
aws.region=${AWS_REGION:eu-north-1}
aws.s3.bucketname=${AWS_BUCKET_NAME:foodies-foodpu}

# ===============================
# FILE UPLOAD
# ===============================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ===============================
# JWT CONFIG
# ===============================
jwt.secret.key=${JWT_SECRET:defaultsecret123}

# ===============================
# RAZORPAY CONFIG
# ===============================
razorpay_key=${RAZORPAY_KEY:dummy}
razorpay_secret=${RAZORPAY_SECRET:dummy}